Table Pengguna {
  id_pengguna int [pk]
  nama varchar
  email varchar
  password varchar
  no_telp varchar
  alamat text
  role varchar
}

Table Kendaraan {
  id_kendaraan int [pk]
  jenis varchar
  merek varchar
  model varchar
  tahun int
  harga int
  spesifikasi text
  kilometer int
  kondisi varchar
  status varchar
}

Table Kategori {
  id_kategori int [pk]
  nama_kategori varchar
}

Table Produk {
  id_produk int [pk]
  nama_produk varchar
  harga_beli int
  harga_jual int
  stok int
  id_kategori int
}

Table Supplier {
  id_supplier int [pk]
  nama_supplier varchar
  alamat text
  no_telp varchar
}

Table Transaksi_Penjualan {
  id_transaksi int [pk]
  tanggal date
  jalur_pembelian varchar
  total_bayar int
  status_transaksi varchar
  id_pelanggan int
  id_admin int
}

Table Detail_Penjualan {
  id_detail_penjualan int [pk]
  id_transaksi int
  id_produk int
  jumlah int
  harga_satuan int
  subtotal int
}

Table Transaksi_Kendaraan {
  id_trx_kendaraan int [pk]
  tanggal date
  harga_deal int
  jalur_pembelian varchar
  status_transaksi varchar
  id_pelanggan int
  id_admin int
  id_kendaraan int
}

Table Pembelian_Barang {
  id_pembelian int [pk]
  tanggal date
  total_biaya int
  id_supplier int
  id_admin int
}

Table Detail_Pembelian {
  id_detail_pembelian int [pk]
  id_pembelian int
  id_produk int
  jumlah int
  harga_beli int
  subtotal int
}

Table Layanan {
  id_layanan int [pk]
  nama_layanan varchar
  jenis varchar
  harga int
}

Table Garasi {
  id_garasi int [pk]
  nama_garasi varchar
  alamat text
  no_telp varchar
}

Table Booking_Layanan {
  id_booking int [pk]
  tanggal_booking date
  jam time
  plat_nomor varchar
  catatan text
  status_booking varchar
  id_pelanggan int
  id_layanan int
  id_garasi int
}

Table Pengeluaran {
  id_pengeluaran int [pk]
  tanggal date
  keterangan varchar
  jumlah int
  id_admin int
}

Ref: Produk.id_kategori > Kategori.id_kategori

Ref: Transaksi_Penjualan.id_pelanggan > Pengguna.id_pengguna
Ref: Transaksi_Penjualan.id_admin > Pengguna.id_pengguna
Ref: Detail_Penjualan.id_transaksi > Transaksi_Penjualan.id_transaksi
Ref: Detail_Penjualan.id_produk > Produk.id_produk

Ref: Transaksi_Kendaraan.id_pelanggan > Pengguna.id_pengguna
Ref: Transaksi_Kendaraan.id_admin > Pengguna.id_pengguna
Ref: Transaksi_Kendaraan.id_kendaraan > Kendaraan.id_kendaraan

Ref: Pembelian_Barang.id_supplier > Supplier.id_supplier
Ref: Pembelian_Barang.id_admin > Pengguna.id_pengguna
Ref: Detail_Pembelian.id_pembelian > Pembelian_Barang.id_pembelian
Ref: Detail_Pembelian.id_produk > Produk.id_produk

Ref: Booking_Layanan.id_pelanggan > Pengguna.id_pengguna
Ref: Booking_Layanan.id_layanan > Layanan.id_layanan
Ref: Booking_Layanan.id_garasi > Garasi.id_garasi

Ref: Pengeluaran.id_admin > Pengguna.id_pengguna
