Table Pengguna {
  id_pengguna int [pk]
  nama varchar
  email varchar
  password varchar
  no_telp varchar
  alamat varchar
  role varchar
}

Table Kendaraan {
  id_kendaraan int [pk]
  jenis varchar
  merek varchar
  model varchar
  tahun int
  harga int
  spesifikasi varchar
  kilometer int
  kondisi varchar
  status varchar
}

Table Kategori {
  id_kategori int [pk]
  nama_kategori varchar
}

Table Produk {
  id_produk int [pk]
  nama_produk varchar
  harga_beli int
  harga_jual int
  stok int
  id_kategori int [ref: > Kategori.id_kategori]
}

Table Supplier {
  id_supplier int [pk]
  nama_supplier varchar
  alamat varchar
  no_telp varchar
}

Table Transaksi_Penjualan {
  id_transaksi int [pk]
  tanggal date
  jalur_pembelian varchar
  total_bayar int
  status_transaksi varchar
  id_pelanggan int [ref: > Pengguna.id_pengguna]
  id_admin int [ref: > Pengguna.id_pengguna]
}

Table Detail_Penjualan {
  id_detail_penjualan int [pk]
  id_transaksi int [ref: > Transaksi_Penjualan.id_transaksi]
  id_produk int [ref: > Produk.id_produk]
  jumlah int
  harga_satuan int
  subtotal int
}

Table Transaksi_Kendaraan {
  id_trx_kendaraan int [pk]
  tanggal date
  harga_deal int
  jalur_pembelian varchar
  status_transaksi varchar
  id_pelanggan int [ref: > Pengguna.id_pengguna]
  id_admin int [ref: > Pengguna.id_pengguna]
  id_kendaraan int [ref: > Kendaraan.id_kendaraan]
}

Table Pembelian_Barang {
  id_pembelian int [pk]
  tanggal date
  total_biaya int
  id_supplier int [ref: > Supplier.id_supplier]
  id_admin int [ref: > Pengguna.id_pengguna]
}

